config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "homes/about" => "homes#about"

  resources :postimages, only: [:new, :create, :index, :show, :destroy] do

    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]


  end

  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :shop_name, presence: true
  validates :image, presence: true

  #引数のidがfavoritesモデルのuser_idに存在するかどうか

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end



  def get_image
    unless image.attached?

      #no_image.jpgが何処にあるか指す
      file_path = Rails.root.join('app/assets/images/no_image.jpg')

      #io: どのファイルを取得するのか
      #image.attach : imageに画像をくっつける
      #image/jpg: jpgの画像をつける
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: "image/jpg")
    end

    #image = return self.image
    #self: .がついている前のものを指す
    image
  end

  # def get_image
  #   if image.attached?
  #     image
  #   else
  #     'no_image.jpg'
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    postimages_path
  end

  def after_sign_out_path_for(resource)
    homes_about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    #post_image_idだと、Couldn't find PostImage without an ID
    #postimage_idで解決
    post_image = PostImage.find(params[:postimage_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to postimage_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:postimage_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to postimage_path(post_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:postimage_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to postimage_path(post_image)
  end

  def destroy
    #Couldn't find PostComment with 'id'=1
    #show.html.erbの記述が <%= link_to "削除", postimage_post_comment_path(post_comment), method: :delete %>になってた
    #正しくは、 <%= link_to "削除", postimage_post_comment_path(post_comment.post_image , post_comment), method: :delete %>
    PostComment.find(params[:id]).destroy
    redirect_to postimage_path(params[:postimage_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def new
    @post_image = PostImage.new
  end


  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to postimages_path
    else
      render :new
    end
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to postimages_path
  end


  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #何故、新しくusers_controllerを作成する必要があるのか？
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
Aboutページ

app/views/homes/top.html.erb
<h1>Topページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshitero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>

        <li>
          <%= link_to "投稿フォーム", new_postimage_path %>
        </li>

        <li>
          <%= link_to "マイページ", user_path(current_user.id) %>
        </li>

        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/postimages/_list.html.erb
<% post_images.each do |post_image| %>

  <div>
    <%= link_to postimage_path(post_image.id) do %>
      <%= image_tag post_image.get_image %>
    <% end %>

    <p>投稿ユーザー画像: <%= image_tag post_image.user.get_profile_image("100x100") %></p>
    <p>ショップ名: <%= post_image.shop_name %></p>
    <p>説明: <%= post_image.caption %></p>
    <p>ユーザーネーム: <%= post_image.user.name %></p>
    <p><%= link_to "#{post_image.post_comments.count}コメント" , postimage_path(post_image.id) %></p>
  </div>
<% end %>
<%= paginate post_images %>

app/views/postimages/index.html.erb
<%= render 'list', post_images: @post_images %>

app/views/postimages/new.html.erb
<h1>画像投稿フォーム</h1>

<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
    <ul>
      <% @post_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

    <%# "/postimagesというurlを入れないと、undefined method `post_images_path'"%>

   <%= form_with model: @post_image,url: "/postimages", local:true do |f| %>
    <h4>画像</h4>

      <%# file_field => ファイルを投稿するフィールド%>
      <%# accept: "image" => 画像ファイルしか投稿出来ないようにする。%>

      <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :shop_name %>
    <h4>説明</h4>
      <%= f.text_area :caption %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/postimages/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名: <%= @post_image.shop_name %></p>
  <p>説明: <%= @post_image.caption %></p>
  <p>投稿ユーザー画像: <%= image_tag @post_image.user.get_profile_image("100x100") %></p>
  <p>ユーザーネーム: <%= @post_image.user.name %></p>
  <p>投稿日: <%= @post_image.created_at.strftime('%Y/%m/%d') %></p>

  <% if @post_image.user == current_user %>
    <%= link_to "削除", postimage_path(@post_image.id), method: :delete %>
  <% end %>

  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to postimage_favorites_path(@post_image), method: :delete do  %>
         ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>

  <% else %>
    <p>
      <%= link_to postimage_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<div>
  <p>コメント件数: <%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image("100x100") %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>

    <% if post_comment.user == current_user %>
      <%= link_to "削除", postimage_post_comment_path(post_comment.post_image , post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>

<div>
<%= form_with model: [@post_image, @post_comment], url: postimage_post_comments_path(@post_image),  local: true do |f| %>
    <%= f.text_area :comment, rows: '5' , placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user , local:true do |f| %>
  <label for = "inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "名前" %>
  <label for ="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image("100x100") %>

  <% if @user == current_user %>
     <p><%= link_to "プロフィール編集", edit_user_path %></p>
  <% end %>
</div>

<%# 違うフォルダに部分テンプレートがあるため、フォルダ名も指定する必要がある %>
<%= render 'postimages/list' , post_images: @post_images %>